language: node_js
node_js:
    - stable
before_install:
    - cd server
install:
    - npm install -g graphcool
    - npm install -g codecov
    - npm install
script:
    - npm test
    - codecov
after_success:
    - graphcool deploy