language: node_js
node_js:
    - stable
before_install:
    - cd server
install:
    - npm install
script:
    - npm test
    - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov
    - codecov
after_success:
    - graphcool deploy --target-prod