language: node_js
node_js:
    - stable
before_install:
    - cd server
install:
    - npm install
script:
    - npm test
    - codecov --disable=gcov
after_success:
    - graphcool deploy --target-prod