language: node_js
node_js:
    - stable
before_install:
    - cd server
install:
    - yarn add -g codecov
    - yarn install
script:
    - npm test
    - codecov
after_success:
    - graphcool deploy