language: node_js
node_js:
    - stable
before_install:
    - cd server
install:
    - npm install
script:
    - npm test
    - istanbul cover _mocha
    - codecov
after_success:
    - graphcool deploy --target-prod